[2024-04-27 20:55:25,265] 198 root -ERROR Error occured while creating data for prediction
[2024-04-27 20:55:25,265] 199 root -ERROR Error occured in python script named [d:/data_science/ml_projects/fpl_data_analysis/src/components/merging_raw_data.py] line number [193] error message [[Errno 13] Permission denied: 'pred_df2.csv']
